# do-not-regen
#
# This has a custom setting: "install-dzil-from-cpan: true", because the
# version of Dist::Zilla in apt will not properly work with "inc" plugins.
name: "dzil matrix"
on:
  workflow_dispatch: ~
  push:
    branches: "*"
    tags-ignore: "*"
  pull_request: ~

jobs:
  build-and-test:
    name: dzil-matrix
    uses: rjbs/dzil-actions/.github/workflows/dzil-matrix.yaml@v0
    with:
      install-dzil-from-cpan: true
